server {
    listen 80;
    server_name localhost;

    # Laravel の公開フォルダ（src/public）を配信する
    root /var/www/html/public;
    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # .php へのリクエストは app コンテナ（PHP-FPM の 9000 番）に渡す
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
